### ISSUE TITLE
The input VCF file is empty or does not exist or the first column (showing the chromosomes) is not a sole number (It shouldn't be chr1!) or you are not running PhaseME on Linux

### ISSUE THREAD

**Issue by wjj666** [smajidian/phaseme#1]
Hi, I want to evaluate my my vcf file (generate with **whatshap**) and then run **python haseme.py quality** command  as shown below: 
> python /***/phaseme/phaseme.py quality ../phased_hic.vcf out /***/phaseme/shapeit.v2.904.3.10.0-693.11.6.el7.x86_64/bin /***/phaseme/1000GP/1000GP_Phase3

but it leads to this error and the vcf file in the out dir is the same as  **phased_hic.vcf**:

> Phaseme is running in  individual  mode.
> The input VCF file at ../phased_hic.vcf is empty or does not exist or the first column (showing the chromosomes) is not a sole number (It shouldn't be chr1!) or you are not running PhaseME on Linux

Is there something wrong with my vcf file? Could you please help me solve this problem? Thank you very much.

**Comment by sinamajidian** [comment]
Hi
Thanks for using our tool.

Could you please share one record of your VCF file, a line that is not started with # ?  
As the output suggests, one reason could be that the values in the first column of your vcf file are chr1 or chr2 or ... chr22. But it should be 1  or 2 or .. 22.

I'm also wondering whether you were able to run PhaseME on the example vcf file (my.vcf) provided [here](https://github.com/smajidian/phaseme/tree/master/example)?  

Regards,
Sina

**Comment by Pharmacogenetecist** [comment]
If you remove chr from VCF file it works and you dont get the above error.
